#!/usr/bin/env python3
"""Generate vectors_data.shard from the certified vector set.

Reads docs/shard_vectors.jsonl (one JSON object per line — decoded NCfg
fields, program words, driver inputs, and the certified per-cycle trace)
and emits shard source embedding every vector as a nullary fn returning a
`Vec` (see emulator.shard).

Driver semantics applied HERE (so the shard driver stays a pure cycle
loop):
  - autopull_pad: the emitted `inputs` list is inputs ++ [0]*autopull_pad
    (mirror of narrow::run_with_stim's padding; the JSONL already zeroes
    the pad when autopull is off);
  - config fields the harness never programs are filled with their spec
    defaults: in_count = 0, status_sel = 0, status_n = 0.

Usage: gen_vectors.py [vectors.jsonl] [out.shard]
Defaults: <repo>/shard_pio/vectors/shard_vectors.jsonl ->
          <repo>/shard_pio/vectors_data.shard
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent  # shard_pio/


def b(v: bool) -> str:
    return "1" if v else "0"


def ilist(xs) -> str:
    if not xs:
        return "Nil"
    return "(list " + " ".join(str(int(x)) for x in xs) + ")"


def name_bytes(name: str) -> str:
    # names are plain ASCII identifiers; embed as a string literal
    assert all(32 < ord(c) < 127 and c != '"' for c in name), name
    return f'"{name}"'


def emit_vec(i: int, v: dict) -> str:
    assert len(v["code"]) == 32
    assert len(v["trace"]) == v["cycles"], v["name"]
    inputs = list(v["inputs"]) + [0] * int(v["autopull_pad"])
    cfg = (
        "(NCfg "
        + ilist(v["code"])
        + f" (CfgWrap {v['wrap_bottom']} {v['wrap_top']})"
        + f" (CfgSide {v['side_count']} {b(v['side_en'])} {b(v['side_pindir'])} {v['sideset_base']})"
        + f" (CfgPins {v['jmp_pin']} {v['in_base']} {v['out_base']} {v['out_count']}"
        + f" {v['set_base']} {v['set_count']} 0)"
        + f" (CfgShift {b(v['autopush'])} {b(v['autopull'])} {v['push_threshold']} {v['pull_threshold']}"
        + f" {b(v['in_shift_right'])} {b(v['out_shift_right'])})"
        + f" (CfgClk {v['clkdiv_int']} {v['clkdiv_frac']})"
        + f" (CfgMisc 0 0 {v['sm_id']} {v['tx_depth']} {v['rx_depth']}))"
    )
    return (
        f"(fn vec_{i} () Vec\n"
        f"  (Vec {name_bytes(v['name'])}\n"
        f"    {cfg}\n"
        f"    {ilist(inputs)}\n"
        f"    {ilist(v['output_pins'])}\n"
        f"    {ilist(v['capture_pins'])}\n"
        f"    {v['stim_mask']}\n"
        f"    {ilist(v['stim_values'])}\n"
        f"    {ilist(v['trace'])}))\n"
    )


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "vectors" / "shard_vectors.jsonl"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else HERE / "vectors_data.shard"
    vecs = [json.loads(line) for line in src.read_text().splitlines() if line.strip()]
    parts = [
        ";;; vectors_data.shard — GENERATED by tools/gen_vectors.py; do not edit.\n"
        f";;; Source: {src.name} ({len(vecs)} vectors).\n\n"
        '(import "emulator.shard")\n(use (:: shard_pio emulator *))\n\n'
    ]
    parts += [emit_vec(i, v) + "\n" for i, v in enumerate(vecs)]
    items = " ".join(f"(vec_{i})" for i in range(len(vecs)))
    parts.append(f"(fn vectors () (List Vec)\n  (list {items}))\n")
    out.write_text("".join(parts))
    print(f"wrote {out} ({len(vecs)} vectors)")


if __name__ == "__main__":
    main()
